services:
  bot:
    container_name: "BlumBot"
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    volumes:
      - .:/app
    networks:
      - blum_network # Make sure to use the same network as the payload server

networks:
  blum_network:
    name: blum_network
    driver: bridge
