services:
  bot:
    container_name: "BlumBot"
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    volumes:
      - .:/app
  payload_server:
    container_name: "BlumPayloadServer"
    build:
      context: ./BlumPayloadGenerator
      dockerfile: Dockerfile.payload
    stop_signal: SIGINT
    restart: unless-stopped
    command: "npm start"
    volumes:
      - ./BlumPayloadGenerator:/app
    ports:
      - "9876:9876"
